const QUESTIONS_POOL = [
  { id:1, subject:'Math', question:'What is 5+7?', options:['12','11','10','13'], answer:0 },
  { id:2, subject:'Physics', question:'Unit of force?', options:['Newton','Joule','Pascal','Watt'], answer:0 },
  { id:3, subject:'Computer', question:'What does HTML stand for?', options:['HyperText Markup Language','Home Tool Markup','Hyperlinks Text Mark','Hyper Transfer Markup'], answer:0 },
  { id:4, subject:'English', question:'Synonym of happy?', options:['joyful','sad','angry','thin'], answer:0 },
  { id:5, subject:'General', question:'Capital of India?', options:['New Delhi','Mumbai','Kolkata','Chennai'], answer:0 },
  { id:6, subject:'Math', question:'Next prime after 7?', options:['11','9','13','17'], answer:0 },
  { id:7, subject:'Physics', question:'Acceleration due to gravity?', options:['9.8','10','8.9','9.2'], answer:0 },
  { id:8, subject:'Computer', question:'Which language is used for styling?', options:['CSS','HTML','Python','Java'], answer:0 },
  { id:9, subject:'English', question:'Past tense of go?', options:['went','goes','going','gone'], answer:0 },
  { id:10, subject:'General', question:'Binary of 5?', options:['101','111','010','100'], answer:0 },
  
  // More questions
  { id:11, subject:'Math', question:'Square of 12?', options:['144','124','134','154'], answer:0 },
  { id:12, subject:'Physics', question:'Speed of light?', options:['3x10^8 m/s','3x10^6 m/s','3x10^5 m/s','3x10^7 m/s'], answer:0 },
  { id:13, subject:'Computer', question:'Which is a backend language?', options:['JavaScript','HTML','Python','CSS'], answer:2 },
  { id:14, subject:'English', question:'Antonym of hot?', options:['cold','warm','heat','burn'], answer:0 },
  { id:15, subject:'General', question:'Largest ocean?', options:['Pacific','Atlantic','Indian','Arctic'], answer:0 },
  { id:16, subject:'Math', question:'Area of circle formula?', options:['πr²','2πr','πd','r²'], answer:0 },
  { id:17, subject:'Physics', question:'Unit of energy?', options:['Joule','Newton','Watt','Tesla'], answer:0 },
  { id:18, subject:'Computer', question:'What is a database?', options:['Collection of data','Programming language','Software','Hardware'], answer:0 },
  { id:19, subject:'English', question:'Plural of child?', options:['children','childs','childes','childer'], answer:0 },
  { id:20, subject:'General', question:'Author of "Harry Potter"?', options:['J.K. Rowling','Tolkien','Enid Blyton','George Orwell'], answer:0 },
  
  { id:21, subject:'Math', question:'Value of pi?', options:['3.1416','3.142','3','22'], answer:0 },
  { id:22, subject:'Physics', question:'Unit of electric current?', options:['Ampere','Volt','Ohm','Watt'], answer:0 },
  { id:23, subject:'Computer', question:'Which is an operating system?', options:['Windows','Python','HTML','Chrome'], answer:0 },
  { id:24, subject:'English', question:'Synonym of fast?', options:['quick','slow','lazy','late'], answer:0 },
  { id:25, subject:'General', question:'President of USA in 2020?', options:['Donald Trump','Joe Biden','Barack Obama','George Bush'], answer:0 },
  { id:26, subject:'Math', question:'7 x 8 = ?', options:['56','54','58','52'], answer:0 },
  { id:27, subject:'Physics', question:'Unit of pressure?', options:['Pascal','Newton','Joule','Watt'], answer:0 },
  { id:28, subject:'Computer', question:'Full form of CPU?', options:['Central Processing Unit','Computer Processing Unit','Central Programming Unit','Compute Power Unit'], answer:0 },
  { id:29, subject:'English', question:'Synonym of intelligent?', options:['smart','dull','slow','lazy'], answer:0 },
  { id:30, subject:'General', question:'First man on moon?', options:['Neil Armstrong','Buzz Aldrin','Yuri Gagarin','John Glenn'], answer:0 },
  
  { id:31, subject:'Math', question:'Cube of 3?', options:['27','9','21','30'], answer:0 },
  { id:32, subject:'Physics', question:'Unit of frequency?', options:['Hertz','Newton','Joule','Watt'], answer:0 },
  { id:33, subject:'Computer', question:'Which is markup language?', options:['HTML','Python','Java','C++'], answer:0 },
  { id:34, subject:'English', question:'Past tense of run?', options:['ran','run','runned','running'], answer:0 },
  { id:35, subject:'General', question:'Country known as Land of Rising Sun?', options:['Japan','China','India','Thailand'], answer:0 },
  { id:36, subject:'Math', question:'Solve: 15 ÷ 3', options:['5','6','4','3'], answer:0 },
  { id:37, subject:'Physics', question:'Unit of work?', options:['Joule','Newton','Pascal','Watt'], answer:0 },
  { id:38, subject:'Computer', question:'Which is a database query language?', options:['SQL','HTML','CSS','JavaScript'], answer:0 },
  { id:39, subject:'English', question:'Antonym of easy?', options:['difficult','simple','light','soft'], answer:0 },
  { id:40, subject:'General', question:'Currency of UK?', options:['Pound','Euro','Dollar','Rupee'], answer:0 },
  
  { id:41, subject:'Math', question:'Value of 2^5?', options:['32','16','64','25'], answer:0 },
  { id:42, subject:'Physics', question:'Acceleration formula?', options:['v-u/t','m*a','f/m','v*t'], answer:0 },
  { id:43, subject:'Computer', question:'Which language is used for Android?', options:['Java','Python','C++','HTML'], answer:0 },
  { id:44, subject:'English', question:'Synonym of angry?', options:['furious','calm','happy','sad'], answer:0 },
  { id:45, subject:'General', question:'Tallest mountain?', options:['Everest','K2','Kangchenjunga','Lhotse'], answer:0 },
  { id:46, subject:'Math', question:'Perimeter of square formula?', options:['4a','a^2','2a','a/4'], answer:0 },
  { id:47, subject:'Physics', question:'Light year measures?', options:['Distance','Time','Speed','Energy'], answer:0 },
  { id:48, subject:'Computer', question:'Which is programming language?', options:['Python','HTML','CSS','SQL'], answer:0 },
  { id:49, subject:'English', question:'Plural of mouse?', options:['mice','mouses','mouse','moose'], answer:0 },
  { id:50, subject:'General', question:'Fastest land animal?', options:['Cheetah','Lion','Tiger','Leopard'], answer:0 }
];
